version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands: #https://learning.getpostman.com/docs/postman/collection-runs/command-line-integration-with-newman/
      - npm install -g newman
      - yum install -y jq

  build:
    commands:
      - cd postman 
      - echo Build started on `date` from dir `pwd`
      - ./runTests.sh

reports:
  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: './postman/newman' # Location of the reports