version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "listify"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iriw7pcgy02w"
s3_prefix = "listify"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"master\""
